#!/usr/bin/env node
"use strict";
const path = require("path"); const { spawn, spawnSync } = require("child_process"); const WebSocket = require("ws");
const ROOT = path.resolve(__dirname, "..");
function check(file) { const r = spawnSync(process.execPath, ["--check", file], { encoding: "utf8" }); if (r.status) throw new Error(`${file}: ${r.stderr || r.stdout}`); }
for (const file of ["server.js", "server/games/minesweeper-duel.js", "server/games/forgotten-mines.js", "js/main.js", "js/net.js", "js/registry.js", "js/games/minesweeper-duel.js", "js/games/minesweeper-duel-logic.js", "js/games/forgotten-mines.js", "js/games/forgotten-mines-logic.js"]) check(path.join(ROOT, file));
const failedStart = spawnSync(process.execPath, ["server.js"], { cwd: ROOT, env: { ...process.env, HOST: "256.256.256.256", PORT: "18777" }, encoding: "utf8", timeout: 3000 });
if (failedStart.status === 0 || !failedStart.stderr.includes("[server] http error")) throw new Error(`startup failure was not reported: ${failedStart.stderr || failedStart.stdout}`);
const net = require("http"); const port = 18000 + Math.floor(Math.random() * 1000); let stdout = ""; const child = spawn(process.execPath, ["server.js"], { cwd: ROOT, env: { ...process.env, PORT: String(port), DATA_DIR: path.join(ROOT, "test-results") }, stdio: ["ignore", "pipe", "pipe"] }); child.stdout.on("data", (chunk) => { stdout += chunk; });
function wait(ms) { return new Promise((resolve) => setTimeout(resolve, ms)); }
async function ready() { for (let i = 0; i < 40; i++) { try { await new Promise((resolve, reject) => { const req = net.get(`http://127.0.0.1:${port}/health`, (res) => { let body = ""; res.on("data", (chunk) => { body += chunk; }); res.on("end", () => { try { const health = JSON.parse(body); res.statusCode === 200 && health.ok === true && Number.isInteger(health.uptimeSeconds) ? resolve() : reject(new Error("not ready")); } catch (error) { reject(error); } }); }); req.on("error", reject); req.setTimeout(100, () => req.destroy()); }); if (!stdout.includes(`[server] 双人小游戏 listening on 0.0.0.0:${port}`)) throw new Error("startup log missing"); return; } catch { await wait(50); } } throw new Error("server did not become ready"); }
function next(ws, type) { return new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error(`timeout: ${type}`)), 4000); ws.on("message", function on(raw) { const m = JSON.parse(raw); if (m.type === type) { clearTimeout(timer); ws.off("message", on); resolve(m); } }); }); }
function close(ws) { return new Promise((resolve) => { if (ws.readyState === WebSocket.CLOSED) return resolve(); ws.once("close", resolve); ws.close(); }); }
(async () => { try { await ready(); const a = new WebSocket(`ws://127.0.0.1:${port}`), b = new WebSocket(`ws://127.0.0.1:${port}`); await Promise.all([new Promise((r) => a.once("open", r)), new Promise((r) => b.once("open", r))]); const createdP = next(a, "created"); a.send(JSON.stringify({ type: "create", gameId: "minesweeper-duel", playerName: "甲" })); const created = await createdP; const startA = next(a, "start"), startB = next(b, "start"); b.send(JSON.stringify({ type: "join", code: created.code, playerName: "乙" })); await Promise.all([startA, startB]); await Promise.all([close(a), close(b)]); console.log("ok smoke: server, room creation, join"); } finally { await new Promise((resolve) => { child.once("close", resolve); child.kill(); }); } })().catch((e) => { child.kill(); console.error(e.message); process.exitCode = 1; });
