#!/usr/bin/env node
"use strict";
const path = require("path"); const { spawn, spawnSync } = require("child_process"); const WebSocket = require("ws");
const ROOT = path.resolve(__dirname, "..");
function check(file) { const r = spawnSync(process.execPath, ["--check", file], { encoding: "utf8" }); if (r.status) throw new Error(`${file}: ${r.stderr || r.stdout}`); }
for (const file of ["server.js", "js/main.js", "js/net.js", "js/registry.js", "js/games/minesweeper-duel.js", "js/games/minesweeper-duel-logic.js"]) check(path.join(ROOT, file));
const net = require("http"); const port = 18000 + Math.floor(Math.random() * 1000); const child = spawn(process.execPath, ["server.js"], { cwd: ROOT, env: { ...process.env, PORT: String(port), DATA_DIR: path.join(ROOT, "test-results") }, stdio: ["ignore", "ignore", "pipe"] });
function wait(ms) { return new Promise((resolve) => setTimeout(resolve, ms)); }
async function ready() { for (let i = 0; i < 40; i++) { try { await new Promise((resolve, reject) => { const req = net.get(`http://127.0.0.1:${port}/health`, (res) => { res.resume(); res.statusCode === 200 ? resolve() : reject(new Error("not ready")); }); req.on("error", reject); req.setTimeout(100, () => req.destroy()); }); return; } catch { await wait(50); } } throw new Error("server did not become ready"); }
function next(ws, type) { return new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error(`timeout: ${type}`)), 4000); ws.on("message", function on(raw) { const m = JSON.parse(raw); if (m.type === type) { clearTimeout(timer); ws.off("message", on); resolve(m); } }); }); }
(async () => { try { await ready(); const a = new WebSocket(`ws://127.0.0.1:${port}`), b = new WebSocket(`ws://127.0.0.1:${port}`); await Promise.all([new Promise((r) => a.once("open", r)), new Promise((r) => b.once("open", r))]); const createdP = next(a, "created"); a.send(JSON.stringify({ type: "create", gameId: "minesweeper-duel", playerName: "甲" })); const created = await createdP; const startA = next(a, "start"), startB = next(b, "start"); b.send(JSON.stringify({ type: "join", code: created.code, playerName: "乙" })); await Promise.all([startA, startB]); a.close(); b.close(); console.log("ok smoke: server, room creation, join"); } finally { child.kill(); await new Promise((resolve) => child.once("close", resolve)); } })().catch((e) => { child.kill(); console.error(e.message); process.exitCode = 1; });
